# Generated by Django 4.1.5 on 2023-02-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lobby",
            name="name",
        ),
    ]
