# Generated by Django 4.1.5 on 2023-01-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0002_remove_name_is_taken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                ("name", models.CharField(max_length=30)),
                ("number", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name="name",
            name="lobby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="names",
                to="welcome.lobby",
            ),
        ),
    ]
