# Generated by Django 4.1.5 on 2023-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome", "0003_lobby_name_lobby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
